language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

install:
  - composer install

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
